[package]
name = "server_tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
tracing = "0.1.44"
tracing-subscriber = "0.3"
tokio-tungstenite = "0.21"
futures-util = "0.3"